"""Keep the Google Sites embed map, and the pages that use it, in step.

    python3 scripts/build-embed-map.py            # write the map, wire the pages
    python3 scripts/build-embed-map.py --check    # non-zero if either is stale

The hub is served from Vercel but read inside Google Sites: every hub page is a
full-page iframe on a matching Google Sites page under
https://ailearninghub.law.stanford.edu. A reader clicking "Tutorials" inside the
frame must move the *browser* to the Google Sites tutorials page, not just swap
the document inside the frame — otherwise the address bar lies, the back button
does nothing useful, and no link a reader copies can be shared.

One map answers both halves of that. This script derives it from the pages that
actually exist, writes it to assets/embed-map.js, and makes sure every page
loads it, so adding a page is still just adding an HTML file.
"""

import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAP_FILE = ROOT / "assets" / "embed-map.js"

# The Google Sites site the hub is framed inside. Paths in the generated map are
# appended to this, so a move to another domain is a one-line change here.
SITE_ORIGIN = "https://ailearninghub.law.stanford.edu"

# Where a remapped link is sent. "_top" moves the whole browser tab to the
# Google Sites page, which is the point of the exercise. If Google ever tightens
# the sandbox it wraps embed code in, top navigation stops working and this
# becomes "_blank" — the link then opens the Google Sites page in a new tab,
# which is worse but not broken. Nothing else needs to change.
LINK_TARGET = "_top"

# Whether a remapped link keeps its #fragment. Google Sites does not forward a
# fragment on its own URL into the iframe it hosts, so a kept fragment would
# promise a section it cannot scroll to. Dropping it lands the reader at the top
# of the right page instead, and keeps the shared URL honest. Set this True only
# if the Google Sites pages themselves grow matching anchors.
KEEP_HASH = False

# How each page behaves when it is being read inside the frame.
#
#   page     — has its own Google Sites page; links to it move the whole tab.
#   inframe  — stays inside the frame. Search is the only one: it is reached by
#              submitting a query string, and Google Sites cannot pass a query
#              string on its own URL through to the iframe, so a Google Sites
#              /search page would always come up empty.
#   private  — not published to Google Sites at all. Maintenance pages.
MODES = {
    "search.html": "inframe",
    "embed-codes.html": "private",
}

# Slugs are the file name without .html, which keeps the map derivable rather
# than hand-kept. Anything that should read differently on the Google Sites side
# goes here, and the Google Sites page URL must match.
SLUGS = {
    # The Google Sites root is its own hand-built landing page, so the hub's
    # landing page is a full page embed alongside it rather than at "/".
    "index.html": "/home",
    "faculty.html": "/faculty-support",
}

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
FRAME_RE = re.compile(r'<iframe[^>]*class="embedFrame"[^>]*src="([^"]+)"', re.S)
BLOCK_RE = re.compile(
    r"\n?<!-- embed-map: generated by scripts/build-embed-map\.py -->.*?"
    r"<script src=\"assets/embed\.js\"></script>\n?",
    re.S,
)

# The two full-page frames hold someone else's site and carry no links of their
# own, so there is nothing on them for the runtime to rewrite.
NO_RUNTIME = {"faculty.html", "ai-upload.html"}

SCRIPT_BLOCK = (
    "\n<!-- embed-map: generated by scripts/build-embed-map.py -->\n"
    '<script src="assets/embed-map.js"></script>\n'
    '<script src="assets/embed.js"></script>\n'
)


def title_of(path):
    """The page's own name, without the two suffixes every title carries."""
    match = TITLE_RE.search(path.read_text())
    if not match:
        return path.stem
    return html.unescape(match.group(1).split("|")[0]).strip()


def slug_for(name):
    return SLUGS.get(name, "/" + name[: -len(".html")])


def frame_for(path):
    """What the Google Sites page should actually frame.

    Two hub pages are nothing but a full-page frame around another site. Framing
    the wrapper from Google Sites would nest three deep to show the same thing,
    so the map records the site those pages carry and Google Sites frames it
    directly. Read out of the page rather than listed here, so it cannot drift
    from what the page itself shows.
    """
    match = FRAME_RE.search(path.read_text())
    return match.group(1) if match else None


def order_key(name):
    # The landing page first, since it is the one page whose Google Sites path
    # is not its own name and the easiest to overlook. The rest read as a list.
    return (0, "") if name == "index.html" else (1, name)


def build_map(pages):
    rows = []
    for page in sorted(pages, key=lambda p: order_key(p.name)):
        name = page.name
        mode = MODES.get(name, "page")
        entry = [f'    {{ file: "{name}"', f'mode: "{mode}"']
        if mode == "page":
            entry.append(f'path: "{slug_for(name)}"')
        entry.append(f'title: "{title_of(page).replace(chr(34), chr(39))}"')
        frame = frame_for(page)
        if mode == "page" and frame:
            entry.append(f'frame: "{frame}"')
        rows.append(", ".join(entry) + " }")
    joined = ",\n".join(rows)
    return f"""// =============================================================================
// GENERATED by scripts/build-embed-map.py — do not edit by hand.
//
// Which Google Sites page holds each hub page. assets/embed.js reads this when
// the hub is being viewed inside the frame, and embed-codes.html reads it to
// print the iframe to paste into each Google Sites page.
// =============================================================================

window.HUB_EMBED_MAP = {{
  siteOrigin: "{SITE_ORIGIN}",
  linkTarget: "{LINK_TARGET}",
  keepHash: {str(KEEP_HASH).lower()},
  pages: [
{joined}
  ]
}};
"""


def wire(page):
    """Put the two script tags at the end of the body, exactly once."""
    text = page.read_text()
    stripped = BLOCK_RE.sub("\n", text)
    # Removing the block leaves the newlines that surrounded it, and re-adding it
    # brings its own — so without this the file grows a blank line per run.
    stripped = re.sub(r"\n+</body>", "\n</body>", stripped)
    if page.name in NO_RUNTIME:
        return stripped
    if "</body>" not in stripped:
        sys.exit(f"{page.name}: no </body> to wire the embed runtime into")
    return stripped.replace("</body>", SCRIPT_BLOCK + "</body>", 1)


def main():
    check = "--check" in sys.argv
    pages = sorted(ROOT.glob("*.html"))
    if not pages:
        sys.exit("no pages found")

    stale = []

    wanted = build_map(pages)
    if not MAP_FILE.exists() or MAP_FILE.read_text() != wanted:
        stale.append(MAP_FILE.name)
        if not check:
            MAP_FILE.write_text(wanted)
            print(f"wrote {MAP_FILE.relative_to(ROOT)}")

    for page in pages:
        text = wire(page)
        if text != page.read_text():
            stale.append(page.name)
            if not check:
                page.write_text(text)
                print(f"wired {page.name}")

    if check and stale:
        sys.exit("out of date: " + ", ".join(stale))
    if check:
        print("embed map is up to date")
    elif not stale:
        print("everything already up to date")


if __name__ == "__main__":
    main()
